name: cea

on:
  watch:
    # Test on star
    types: [started]
  schedule:
    # It's Universal Coordinated Time, +8 timezone is what we need
    - cron: '0 22 * * *'

jobs:
  cea:
    runs-on: ubuntu-latest
    steps:
      - name: 安装 cea
        run: sudo npm i -g @beetcb/cea > /dev/null

      - name: 加载学校及用户信息
        run: cea load
        env: # Or as an environment variable
          users: ${{ secrets.users }}
          school: ${{ secrets.school }}

      - name: 执行签到
        run: cea sign
